### ISSUE TITLE
How can I use enumeration?

### ISSUE THREAD

**Issue by PouryaMontakhab** [fenomeno83/graphql-dotnet-auto-types#2]
Hi.
 I want to use enums inside my models but I cant resolve them. 
is there any way?

**Comment by fenomeno83** [comment]
hi.
You can see example here

https://github.com/fenomeno83/graphql-dotnet-globalization-demo
and in particular:
https://github.com/fenomeno83/graphql-dotnet-globalization-demo/blob/master/GraphQL.Globalization.Entities/Models/Enums.cs

You have "FakeEnum" model

It is used here (use integer value in graphql request)

https://github.com/fenomeno83/graphql-dotnet-globalization-demo/blob/master/GraphQL.Globalization.Api/GraphQLSchema/Mutations/Groups/TestGroupMutations.cs

**Comment by PouryaMontakhab** [comment]
"FakeEnum" is changed to IntGraphType after resolving. I want to show as enum in my schema
    On Monday, April 4, 2022, 04:00:47 PM GMT+4:30, fenomeno83 ***@***.***> wrote:  
 
 


hi.
You can see example here

https://github.com/fenomeno83/graphql-dotnet-globalization-demo
and in particular:
https://github.com/fenomeno83/graphql-dotnet-globalization-demo/blob/master/GraphQL.Globalization.Entities/Models/Enums.cs

You have "FakeEnum" model

**Comment by fenomeno83** [comment]
hi...this is not supported... enums is converted to intgraphtype as you say

**Comment by PouryaMontakhab** [comment]
Thank you.
